/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with username/email + password (sets auth cookies) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token and issue a new access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh token and clear auth cookies (idempotent) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit logs (filter by action/user/entity/date range) */
        get: operations["AuditLogsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an audit log with its old/new snapshots (spec §56) */
        get: operations["AuditLogsController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List students (paginated; search by code/name, filter by status/year) */
        get: operations["StudentsController_list"];
        put?: never;
        /** Create a student */
        post: operations["StudentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a CSV/XLSX import file without writing anything (spec §8)
         * @description Multipart field "file". Header: student_code,first_name,last_name,birth_date,year[,email] — max 1000 rows.
         */
        post: operations["StudentsController_importPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a CSV/XLSX file (re-validates, then applies the valid rows)
         * @description Multipart field "file". Existing student_code rows are updated (upsert); invalid rows are skipped and reported.
         */
        post: operations["StudentsController_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a student by id */
        get: operations["StudentsController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a student (no hard delete — spec §35) */
        patch: operations["StudentsController_update"];
        trace?: never;
    };
    "/api/v1/students/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable a student (status INACTIVE — this is the "delete", spec §35) */
        post: operations["StudentsController_disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable a student (status ACTIVE) */
        post: operations["StudentsController_enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{id}/unlink-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlink the student LINE account (admin reset, spec §7.1) */
        post: operations["StudentsController_unlinkLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beacons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List beacons (paginated; search by hwid/name/location, filter by status) */
        get: operations["BeaconsController_list"];
        put?: never;
        /** Register a beacon (spec §13 — HWID must be issued by LINE) */
        post: operations["BeaconsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beacons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a beacon by id */
        get: operations["BeaconsController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a beacon (no hard delete — spec §35) */
        patch: operations["BeaconsController_update"];
        trace?: never;
    };
    "/api/v1/beacons/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable a beacon (status INACTIVE — this is the "delete", spec §35) */
        post: operations["BeaconsController_disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beacons/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable a beacon (status ACTIVE) */
        post: operations["BeaconsController_enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beacon-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List beacon logs (paginated; filter by hwid/student/status/date range — spec §46) */
        get: operations["BeaconLogsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beacon-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a beacon log with its raw LINE payload (spec §18) */
        get: operations["BeaconLogsController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List activities (paginated; own activities for organizers, all for admins — spec §29) */
        get: operations["ActivitiesController_list"];
        put?: never;
        /** Create a DRAFT activity (spec §11) */
        post: operations["ActivitiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an activity with its linked beacons */
        get: operations["ActivitiesController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an activity (status only moves via publish/cancel — spec §35) */
        patch: operations["ActivitiesController_update"];
        trace?: never;
    };
    "/api/v1/activities/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DRAFT → PUBLISHED (needs ≥1 beacon and a non-overlapping window — spec §38, §54.4) */
        post: operations["ActivitiesController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an activity (status CANCELLED — this is the "delete", spec §35) */
        post: operations["ActivitiesController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{id}/beacons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the beacons linked to an activity (spec §14) */
        get: operations["ActivitiesController_listBeacons"];
        put?: never;
        /** Link a beacon (overlap-checked when the activity is PUBLISHED — spec §38) */
        post: operations["ActivitiesController_linkBeacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{id}/beacons/{beaconId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink a beacon (idempotent) */
        delete: operations["ActivitiesController_unlinkBeacon"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{id}/attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an activity's attendance rows (search by student code/name — spec §25) */
        get: operations["AttendanceController_listByActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{id}/attendances/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual check-in — organizer selects status + reason, allowed outside the window (spec §19) */
        post: operations["AttendanceController_manualCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{id}/attendances/{attendanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Manually change an attendance status (audited — spec §56) */
        patch: operations["AttendanceController_updateAttendance"];
        trace?: never;
    };
    "/api/v1/students/{id}/attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A student's attendance history across activities (admin only — spec §27, §35) */
        get: operations["AttendanceController_listByStudent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (paginated; search by email/username, filter by role/status) */
        get: operations["UsersController_list"];
        put?: never;
        /** Create an organizer/admin account (spec §28) */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["UsersController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update email/username/role (password + status have dedicated endpoints) */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/v1/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable a user (status INACTIVE — the "delete"; revokes sessions) */
        post: operations["UsersController_disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable a user (status ACTIVE) */
        post: operations["UsersController_enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a user's password (revokes all their sessions) */
        post: operations["UsersController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview stats + recent/open-checkin activities (own activities for organizers) */
        get: operations["DashboardController_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity attendance report — header + §44 counts + full list */
        get: operations["ReportsController_activityReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/activities/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the activity report as CSV or Excel (spec §44) */
        get: operations["ReportsController_exportActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A student's attendance report across activities (admin only — spec §27, §35) */
        get: operations["ReportsController_studentReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LINE webhook (beacon events)
         * @description Signature-verified LINE callback. Always answers 200 once the signature is valid and events are persisted; processing continues in the background (spec §36).
         */
        post: operations["LineWebhookController_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link this LINE account to a student (student code + birth date)
         * @description Body: { studentCode (12 digits), birthDate (DDMMYYYY ค.ศ.) }. Max 5 failed attempts per student code per hour (429); conflicts answer 409.
         */
        post: operations["LineLinkController_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlink the caller's own LINE account (idempotent) */
        post: operations["LineLinkController_unlink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Student profile + LINE link status of the caller (LIFF) */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's own attendance history, newest first (created by the attendance engine (spec §10)) */
        get: operations["MeController_attendances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description Username or email
             * @example admin
             */
            username_or_email: string;
            /** @example change-me-admin */
            password: string;
        };
        UserProfileDto: {
            /** @example clx…cuid */
            id: string;
            /** @example admin@example.com */
            email: string;
            /** @example admin */
            username: string;
            /**
             * @example ADMIN
             * @enum {string}
             */
            role: "ADMIN" | "ORGANIZER";
        };
        AuditActorDto: {
            id: string;
            /** @example admin */
            username: string;
        };
        AuditLogResponseDto: {
            id: string;
            /** @description null เมื่อ actor เป็นนักศึกษา (LIFF self-service, spec §56) */
            user: components["schemas"]["AuditActorDto"] | null;
            /** @example STUDENT_CREATED */
            action: string;
            /** @example STUDENT */
            entityType: string;
            entityId: string;
            /** @example 2026-08-22T00:00:00.000Z */
            createdAt: string;
        };
        AuditLogDetailDto: {
            id: string;
            /** @description null เมื่อ actor เป็นนักศึกษา (LIFF self-service, spec §56) */
            user: components["schemas"]["AuditActorDto"] | null;
            /** @example STUDENT_CREATED */
            action: string;
            /** @example STUDENT */
            entityType: string;
            entityId: string;
            /** @example 2026-08-22T00:00:00.000Z */
            createdAt: string;
            oldValue: Record<string, never> | null;
            newValue: Record<string, never> | null;
        };
        StudentResponseDto: {
            id: string;
            /** @example 660112230038 */
            studentCode: string;
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /**
             * @description วันเกิด (ค.ศ.) รูปแบบ YYYY-MM-DD
             * @example 2004-01-01
             */
            birthDate: string;
            /** @example 3 */
            year: number;
            /** @example student@example.com */
            email: Record<string, never> | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** @description เชื่อมต่อบัญชี LINE แล้วหรือไม่ */
            lineLinked: boolean;
            /** @example 2026-08-22T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-08-22T00:00:00.000Z */
            updatedAt: string;
        };
        CreateStudentDto: {
            /**
             * @description รหัสนักศึกษา ตัวเลข 12 หลัก
             * @example 660112230038
             */
            studentCode: string;
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /**
             * @description วันเกิด (ค.ศ.) รูปแบบ YYYY-MM-DD
             * @example 2004-01-01
             */
            birthDate: string;
            /**
             * @description ชั้นปี 1–8
             * @example 3
             */
            year: number;
            /** @example student@example.com */
            email?: string | null;
        };
        UpdateStudentDto: {
            /**
             * @description รหัสนักศึกษา ตัวเลข 12 หลัก
             * @example 660112230038
             */
            studentCode?: string;
            /** @example Somchai */
            firstName?: string;
            /** @example Jaidee */
            lastName?: string;
            /**
             * @description วันเกิด (ค.ศ.) รูปแบบ YYYY-MM-DD
             * @example 2004-01-01
             */
            birthDate?: string;
            /**
             * @description ชั้นปี 1–8
             * @example 3
             */
            year?: number;
            /** @example student@example.com */
            email?: string | null;
        };
        BeaconResponseDto: {
            id: string;
            /** @example 32af519e88 */
            hwid: string;
            /** @example CS Room 101 */
            name: string;
            /** @example CS101 */
            location: Record<string, never> | null;
            /** @example บีคอนห้อง CS101 */
            description: Record<string, never> | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
            /** @example 2026-08-22T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-08-22T00:00:00.000Z */
            updatedAt: string;
        };
        CreateBeaconDto: {
            /**
             * @description HWID ที่ LINE ออกให้ เลขฐานสิบหก 10 ตัวอักษร
             * @example 32af519e88
             */
            hwid: string;
            /** @example CS Room 101 */
            name: string;
            /** @example CS101 */
            location?: string | null;
            /** @example บีคอนห้อง CS101 */
            description?: string | null;
        };
        UpdateBeaconDto: {
            /**
             * @description HWID ที่ LINE ออกให้ เลขฐานสิบหก 10 ตัวอักษร
             * @example 32af519e88
             */
            hwid?: string;
            /** @example CS Room 101 */
            name?: string;
            /** @example CS101 */
            location?: string | null;
            /** @example บีคอนห้อง CS101 */
            description?: string | null;
            /**
             * @description เปลี่ยนสถานะได้ทุกค่า (เช่น MAINTENANCE) — สถานะ ACTIVE/INACTIVE มี endpoint เฉพาะ
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
        };
        BeaconLogStudentDto: {
            id: string;
            /** @example 660112230038 */
            studentCode: string;
            /** @example Somchai Jaidee */
            name: string;
        };
        BeaconLogBeaconDto: {
            id: string;
            /** @example CS Room 101 */
            name: string;
        };
        BeaconLogResponseDto: {
            id: string;
            /** @example U1234567890abcdef1234567890abcdef */
            lineUserId: string;
            student: components["schemas"]["BeaconLogStudentDto"] | null;
            beacon: components["schemas"]["BeaconLogBeaconDto"] | null;
            /** @example 32af519e88 */
            hwid: string;
            /** @example enter */
            eventType: string;
            /** @example 2026-08-22T00:00:00.000Z */
            eventTimestamp: string;
            /** @example 22babee0-bdbe-43a5-a29a-ac8e6d1ba3c7 */
            webhookEventId: string;
            /** @enum {string} */
            processingStatus: "RECEIVED" | "PROCESSED" | "DUPLICATE" | "UNKNOWN_USER" | "UNKNOWN_BEACON" | "NO_ACTIVE_ACTIVITY" | "OUTSIDE_CHECKIN_WINDOW" | "ERROR";
            /**
             * @description เวลาที่ server รับ webhook
             * @example 2026-08-22T00:00:00.000Z
             */
            createdAt: string;
        };
        BeaconLogDetailDto: {
            id: string;
            /** @example U1234567890abcdef1234567890abcdef */
            lineUserId: string;
            student: components["schemas"]["BeaconLogStudentDto"] | null;
            beacon: components["schemas"]["BeaconLogBeaconDto"] | null;
            /** @example 32af519e88 */
            hwid: string;
            /** @example enter */
            eventType: string;
            /** @example 2026-08-22T00:00:00.000Z */
            eventTimestamp: string;
            /** @example 22babee0-bdbe-43a5-a29a-ac8e6d1ba3c7 */
            webhookEventId: string;
            /** @enum {string} */
            processingStatus: "RECEIVED" | "PROCESSED" | "DUPLICATE" | "UNKNOWN_USER" | "UNKNOWN_BEACON" | "NO_ACTIVE_ACTIVITY" | "OUTSIDE_CHECKIN_WINDOW" | "ERROR";
            /**
             * @description เวลาที่ server รับ webhook
             * @example 2026-08-22T00:00:00.000Z
             */
            createdAt: string;
            /** @description เหตุการณ์ดิบจาก LINE ตามที่รับมา (debug/audit, spec §18) */
            rawPayload: Record<string, never>;
        };
        ActivityCreatorDto: {
            id: string;
            /** @example somorganizer */
            username: string;
        };
        ActivityResponseDto: {
            id: string;
            /** @example Orientation 2026 */
            name: string;
            description: Record<string, never> | null;
            /** @example ห้องประชุมใหญ่ */
            location: Record<string, never> | null;
            /** @example 2026-09-01T13:00:00.000Z */
            startAt: string;
            /** @example 2026-09-01T16:00:00.000Z */
            endAt: string;
            /** @example 2026-09-01T12:30:00.000Z */
            checkinOpenAt: string;
            /** @example 2026-09-01T14:00:00.000Z */
            lateAt: string;
            /** @example 2026-09-01T15:00:00.000Z */
            checkinCloseAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            /** @enum {string} */
            timeState: "UPCOMING" | "CHECKIN_OPEN" | "ONGOING" | "COMPLETED";
            createdBy: string;
            creator: components["schemas"]["ActivityCreatorDto"];
            /** @description จำนวนบีคอนที่ลิงก์อยู่ */
            beaconCount: number;
            /** @example 2026-08-22T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-08-22T00:00:00.000Z */
            updatedAt: string;
        };
        AttendanceSummaryDto: {
            /** @description นักศึกษา ACTIVE ทั้งหมด (spec §24) */
            totalStudents: number;
            present: number;
            late: number;
            excused: number;
            /** @description คำนวณ: Total − Present − Late − Excused (ไม่ persist, spec §44) */
            absent: number;
        };
        ActivityDetailDto: {
            id: string;
            /** @example Orientation 2026 */
            name: string;
            description: Record<string, never> | null;
            /** @example ห้องประชุมใหญ่ */
            location: Record<string, never> | null;
            /** @example 2026-09-01T13:00:00.000Z */
            startAt: string;
            /** @example 2026-09-01T16:00:00.000Z */
            endAt: string;
            /** @example 2026-09-01T12:30:00.000Z */
            checkinOpenAt: string;
            /** @example 2026-09-01T14:00:00.000Z */
            lateAt: string;
            /** @example 2026-09-01T15:00:00.000Z */
            checkinCloseAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            /** @enum {string} */
            timeState: "UPCOMING" | "CHECKIN_OPEN" | "ONGOING" | "COMPLETED";
            createdBy: string;
            creator: components["schemas"]["ActivityCreatorDto"];
            /** @description จำนวนบีคอนที่ลิงก์อยู่ */
            beaconCount: number;
            /** @example 2026-08-22T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-08-22T00:00:00.000Z */
            updatedAt: string;
            beacons: components["schemas"]["BeaconResponseDto"][];
            attendanceSummary: components["schemas"]["AttendanceSummaryDto"];
        };
        CreateActivityDto: {
            /** @example Orientation 2026 */
            name: string;
            /** @example กิจกรรมต้อนรับนักศึกษาใหม่ */
            description?: string | null;
            /** @example ห้องประชุมใหญ่ */
            location?: string | null;
            /**
             * @description เวลาเริ่มกิจกรรม (UTC)
             * @example 2026-09-01T13:00:00.000Z
             */
            startAt: string;
            /**
             * @description เวลาสิ้นสุดกิจกรรม (UTC)
             * @example 2026-09-01T16:00:00.000Z
             */
            endAt: string;
            /**
             * @description เวลาเปิดเช็คชื่อ (UTC)
             * @example 2026-09-01T12:30:00.000Z
             */
            checkinOpenAt: string;
            /**
             * @description เกณฑ์มาสาย — เช็คหลังเวลานี้ถือว่า LATE (UTC)
             * @example 2026-09-01T14:00:00.000Z
             */
            lateAt: string;
            /**
             * @description เวลาปิดเช็คชื่อ (UTC)
             * @example 2026-09-01T15:00:00.000Z
             */
            checkinCloseAt: string;
        };
        UpdateActivityDto: {
            /** @example Orientation 2026 */
            name?: string;
            /** @example กิจกรรมต้อนรับนักศึกษาใหม่ */
            description?: string | null;
            /** @example ห้องประชุมใหญ่ */
            location?: string | null;
            /**
             * @description เวลาเริ่มกิจกรรม (UTC)
             * @example 2026-09-01T13:00:00.000Z
             */
            startAt?: string;
            /**
             * @description เวลาสิ้นสุดกิจกรรม (UTC)
             * @example 2026-09-01T16:00:00.000Z
             */
            endAt?: string;
            /**
             * @description เวลาเปิดเช็คชื่อ (UTC)
             * @example 2026-09-01T12:30:00.000Z
             */
            checkinOpenAt?: string;
            /**
             * @description เกณฑ์มาสาย — เช็คหลังเวลานี้ถือว่า LATE (UTC)
             * @example 2026-09-01T14:00:00.000Z
             */
            lateAt?: string;
            /**
             * @description เวลาปิดเช็คชื่อ (UTC)
             * @example 2026-09-01T15:00:00.000Z
             */
            checkinCloseAt?: string;
        };
        LinkBeaconDto: {
            /** @description รหัสบีคอน (id) ที่จะลิงก์กับกิจกรรม */
            beaconId: string;
        };
        AttendanceStudentDto: {
            id: string;
            /** @example 660112230038 */
            studentCode: string;
            /** @example Somchai Jaidee */
            name: string;
        };
        AttendanceBeaconDto: {
            id: string;
            /** @example CS Room 101 */
            name: string;
            /** @example 32af519e88 */
            hwid: string;
        };
        AttendanceActorDto: {
            id: string;
            /** @example somchai */
            username: string;
        };
        AttendanceRowDto: {
            id: string;
            student: components["schemas"]["AttendanceStudentDto"];
            /** @example 2026-09-01T01:00:00.000Z */
            checkInAt: string;
            /** @enum {string} */
            status: "PRESENT" | "LATE" | "ABSENT" | "EXCUSED";
            /** @enum {string} */
            checkinMethod: "BEACON" | "MANUAL";
            beacon: components["schemas"]["AttendanceBeaconDto"] | null;
            checkedInBy: components["schemas"]["AttendanceActorDto"] | null;
            /** @example นักศึกษาปิด Bluetooth */
            manualReason: Record<string, never> | null;
            /** @example 2026-09-01T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-01T00:00:00.000Z */
            updatedAt: string;
        };
        ManualCheckinDto: {
            /** @description รหัสนักศึกษา (id) ที่เช็คชื่อ */
            studentId: string;
            /**
             * @description สถานะที่ organizer เลือก
             * @enum {string}
             */
            status: "PRESENT" | "LATE" | "EXCUSED";
            /**
             * @description เหตุผลที่ต้องเช็คชื่อแทน (spec §19)
             * @example นักศึกษาปิด Bluetooth
             */
            manualReason: string;
        };
        UpdateAttendanceDto: {
            /** @enum {string} */
            status: "PRESENT" | "LATE" | "ABSENT" | "EXCUSED";
        };
        StudentAttendanceRowDto: {
            id: string;
            activityId: string;
            /** @example Git & GitHub Workshop */
            activityName: string;
            /** @example 2026-09-01T01:00:00.000Z */
            checkInAt: string;
            /** @enum {string} */
            status: "PRESENT" | "LATE" | "ABSENT" | "EXCUSED";
            /** @enum {string} */
            checkinMethod: "BEACON" | "MANUAL";
            beacon: components["schemas"]["AttendanceBeaconDto"] | null;
            checkedInBy: components["schemas"]["AttendanceActorDto"] | null;
            manualReason: Record<string, never> | null;
        };
        UserResponseDto: {
            id: string;
            /** @example organizer@example.com */
            email: string;
            /** @example somorganizer */
            username: string;
            /** @enum {string} */
            role: "ADMIN" | "ORGANIZER";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** @example 2026-08-22T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-08-22T00:00:00.000Z */
            updatedAt: string;
        };
        CreateUserDto: {
            /** @example organizer@example.com */
            email: string;
            /** @example somorganizer */
            username: string;
            /** @description รหัสผ่าน (argon2 ตาม design doc) */
            password: string;
            /**
             * @description บทบาท (spec §28 Assign Role)
             * @enum {string}
             */
            role: "ADMIN" | "ORGANIZER";
        };
        UpdateUserDto: {
            /** @example organizer@example.com */
            email?: string;
            /** @example somorganizer */
            username?: string;
            /** @description รหัสผ่าน (argon2 ตาม design doc) */
            password?: string;
            /**
             * @description บทบาท (spec §28 Assign Role)
             * @enum {string}
             */
            role?: "ADMIN" | "ORGANIZER";
        };
        ResetPasswordDto: {
            /** @description รหัสผ่านใหม่ */
            newPassword: string;
        };
        TodayStatsDto: {
            /** @description กิจกรรมที่เริ่มวันนี้ (ตามวันประเทศไทย) */
            activities: number;
            /** @description การเช็คชื่อที่เกิดวันนี้ */
            checkins: number;
            present: number;
            late: number;
        };
        RecentActivityDto: {
            id: string;
            /** @example Orientation 2026 */
            name: string;
            /** @example 2026-09-01T13:00:00.000Z */
            startAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            /** @enum {string} */
            timeState: "UPCOMING" | "CHECKIN_OPEN" | "ONGOING" | "COMPLETED";
        };
        OpenCheckinActivityDto: {
            id: string;
            /** @example Git & GitHub Workshop */
            name: string;
            /** @example 2026-09-01T12:30:00.000Z */
            checkinOpenAt: string;
            /** @example 2026-09-01T14:00:00.000Z */
            lateAt: string;
            /** @example 2026-09-01T15:00:00.000Z */
            checkinCloseAt: string;
            /** @description จำนวน PRESENT สะสมของกิจกรรมนี้ */
            present: number;
            /** @description จำนวน LATE สะสมของกิจกรรมนี้ */
            late: number;
        };
        DashboardResponseDto: {
            today: components["schemas"]["TodayStatsDto"];
            totalActivities: number;
            /** @description กิจกรรมล่าสุด 5 รายการ */
            recentActivities: components["schemas"]["RecentActivityDto"][];
            /** @description กิจกรรมที่กำลังเปิดเช็คชื่อ (เผยแพร่ + อยู่ในหน้าต่างเช็คชื่อตอนนี้) */
            openCheckinActivities: components["schemas"]["OpenCheckinActivityDto"][];
        };
        ActivityReportActivityDto: {
            id: string;
            /** @example Orientation 2026 */
            name: string;
            /** @example 2026-09-01T13:00:00.000Z */
            startAt: string;
            /** @example 2026-09-01T16:00:00.000Z */
            endAt: string;
            /** @example 2026-09-01T12:30:00.000Z */
            checkinOpenAt: string;
            /** @example 2026-09-01T15:00:00.000Z */
            checkinCloseAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            organizer: components["schemas"]["ActivityCreatorDto"];
        };
        ActivityReportDto: {
            activity: components["schemas"]["ActivityReportActivityDto"];
            summary: components["schemas"]["AttendanceSummaryDto"];
            attendances: components["schemas"]["AttendanceRowDto"][];
        };
        StudentReportStudentDto: {
            id: string;
            /** @example 660112230038 */
            studentCode: string;
            /** @example Somchai Jaidee */
            name: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        StudentReportSummaryDto: {
            /** @description จำนวนรายการเช็คชื่อทั้งหมด */
            total: number;
            present: number;
            late: number;
            excused: number;
        };
        StudentReportDto: {
            student: components["schemas"]["StudentReportStudentDto"];
            summary: components["schemas"]["StudentReportSummaryDto"];
            attendances: components["schemas"]["StudentAttendanceRowDto"][];
        };
        LinkLineDto: {
            /**
             * @description รหัสนักศึกษา ตัวเลข 12 หลัก
             * @example 660112230038
             */
            studentCode: string;
            /**
             * @description วันเดือนปีเกิด ตัวเลข 8 หลัก DDMMYYYY ปี ค.ศ.
             * @example 01012004
             */
            birthDate: string;
        };
        StudentProfileDto: {
            id: string;
            /** @example 660112230038 */
            studentCode: string;
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /**
             * @description วันเกิด (ค.ศ.) รูปแบบ YYYY-MM-DD
             * @example 2004-01-01
             */
            birthDate: string;
            /** @example 3 */
            year: number;
            /** @example student@example.com */
            email: Record<string, never> | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        LineLinkInfoDto: {
            /** @example U91AFXXXXXXXX */
            lineUserId: string;
            /** @example Somchai */
            displayName: Record<string, never> | null;
            /** @example https://profile.line-scdn.net/... */
            pictureUrl: Record<string, never> | null;
            /** @example 2026-08-22T00:00:00.000Z */
            linkedAt: string;
        };
        MeResponseDto: {
            /** @description บัญชี LINE นี้เชื่อมกับนักศึกษาแล้วหรือไม่ */
            linked: boolean;
            student: components["schemas"]["StudentProfileDto"] | null;
            line: components["schemas"]["LineLinkInfoDto"] | null;
        };
        AttendanceItemDto: {
            id: string;
            activityId: string;
            /** @example ปฐมนิเทศน์นักศึกษาใหม่ */
            activityName: string;
            /**
             * @description เวลาเช็คชื่อ (UTC) แสดงผลเป็น Asia/Bangkok
             * @example 2026-08-22T02:00:00.000Z
             */
            checkInAt: string;
            /** @enum {string} */
            status: "PRESENT" | "LATE" | "ABSENT" | "EXCUSED";
            /** @enum {string} */
            checkinMethod: "BEACON" | "MANUAL";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
        };
    };
    AuditLogsController_list: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "created_at" | "action" | "entity_type";
                order?: "asc" | "desc";
                action?: "LOGIN" | "STUDENT_CREATED" | "STUDENT_UPDATED" | "STUDENT_DISABLED" | "STUDENT_ENABLED" | "STUDENT_IMPORTED" | "LINE_ACCOUNT_LINKED" | "LINE_ACCOUNT_UNLINKED" | "BEACON_CREATED" | "BEACON_UPDATED" | "BEACON_DISABLED" | "BEACON_ENABLED" | "ACTIVITY_CREATED" | "ACTIVITY_UPDATED" | "ACTIVITY_PUBLISHED" | "ACTIVITY_CANCELLED" | "ACTIVITY_BEACON_LINKED" | "ACTIVITY_BEACON_UNLINKED" | "ATTENDANCE_MANUAL_CREATED" | "ATTENDANCE_UPDATED" | "USER_CREATED" | "USER_UPDATED" | "USER_DISABLED" | "USER_ENABLED" | "USER_PASSWORD_RESET";
                /** @description กรองตามผู้ใช้ (id) */
                userId?: string;
                /** @description กรองตามชนิด entity */
                entityType?: string;
                /** @description ช่วงเวลา (เริ่มต้น) */
                from?: string;
                /** @description ช่วงเวลา (สิ้นสุด) */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponseDto"][];
                };
            };
        };
    };
    AuditLogsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogDetailDto"];
                };
            };
        };
    };
    StudentsController_list: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "created_at" | "updated_at" | "student_code" | "first_name" | "last_name" | "year" | "status";
                order?: "asc" | "desc";
                status?: "ACTIVE" | "INACTIVE";
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"][];
                };
            };
        };
    };
    StudentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    StudentsController_importPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    StudentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    StudentsController_disable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    StudentsController_enable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    StudentsController_unlinkLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponseDto"];
                };
            };
        };
    };
    BeaconsController_list: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "created_at" | "updated_at" | "hwid" | "name" | "status";
                order?: "asc" | "desc";
                status?: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"][];
                };
            };
        };
    };
    BeaconsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBeaconDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"];
                };
            };
        };
    };
    BeaconsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"];
                };
            };
        };
    };
    BeaconsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBeaconDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"];
                };
            };
        };
    };
    BeaconsController_disable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"];
                };
            };
        };
    };
    BeaconsController_enable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"];
                };
            };
        };
    };
    BeaconLogsController_list: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "created_at" | "event_timestamp" | "hwid" | "processing_status";
                order?: "asc" | "desc";
                /** @description กรองตรงตาม HWID */
                hwid?: string;
                /** @description กรองตามรหัสนักศึกษา (id) */
                studentId?: string;
                /** @description กรองตามกิจกรรม — แสดงเฉพาะ log ของบีคอนที่ลิงก์กับกิจกรรมนี้ (spec §24) */
                activityId?: string;
                /** @description สถานะการประมวลผล */
                status?: "RECEIVED" | "PROCESSED" | "DUPLICATE" | "UNKNOWN_USER" | "UNKNOWN_BEACON" | "NO_ACTIVE_ACTIVITY" | "OUTSIDE_CHECKIN_WINDOW" | "ERROR";
                /** @description ช่วงเวลาเริ่มต้น (เทียบกับ event timestamp ตามสเปก §6) */
                from?: string;
                /** @description ช่วงเวลาสิ้นสุด */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconLogResponseDto"][];
                };
            };
        };
    };
    BeaconLogsController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconLogDetailDto"];
                };
            };
        };
    };
    ActivitiesController_list: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "created_at" | "updated_at" | "name" | "start_at" | "status";
                order?: "asc" | "desc";
                status?: "DRAFT" | "PUBLISHED" | "CANCELLED";
                /** @description กรองตามผู้สร้าง (id) — มีความหมายเต็มที่กับ Admin */
                createdById?: string;
                /** @description ช่วงเวลาเริ่มกิจกรรม (เริ่มต้น) */
                from?: string;
                /** @description ช่วงเวลาเริ่มกิจกรรม (สิ้นสุด) */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponseDto"][];
                };
            };
        };
    };
    ActivitiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetailDto"];
                };
            };
        };
    };
    ActivitiesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetailDto"];
                };
            };
        };
    };
    ActivitiesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetailDto"];
                };
            };
        };
    };
    ActivitiesController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetailDto"];
                };
            };
        };
    };
    ActivitiesController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetailDto"];
                };
            };
        };
    };
    ActivitiesController_listBeacons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"][];
                };
            };
        };
    };
    ActivitiesController_linkBeacon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkBeaconDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"];
                };
            };
        };
    };
    ActivitiesController_unlinkBeacon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                beaconId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeaconResponseDto"];
                };
            };
        };
    };
    AttendanceController_listByActivity: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "check_in_at" | "status" | "method" | "created_at";
                order?: "asc" | "desc";
                status?: "PRESENT" | "LATE" | "EXCUSED";
                method?: "BEACON" | "MANUAL";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRowDto"][];
                };
            };
        };
    };
    AttendanceController_manualCheckin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualCheckinDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRowDto"];
                };
            };
        };
    };
    AttendanceController_updateAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                attendanceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttendanceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRowDto"];
                };
            };
        };
    };
    AttendanceController_listByStudent: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "check_in_at" | "status" | "method" | "created_at";
                order?: "asc" | "desc";
                status?: "PRESENT" | "LATE" | "EXCUSED";
                method?: "BEACON" | "MANUAL";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentAttendanceRowDto"][];
                };
            };
        };
    };
    UsersController_list: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: "created_at" | "updated_at" | "email" | "username" | "role" | "status";
                order?: "asc" | "desc";
                role?: "ADMIN" | "ORGANIZER";
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_disable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_enable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    DashboardController_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
        };
    };
    ReportsController_activityReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityReportDto"];
                };
            };
        };
    };
    ReportsController_exportActivity: {
        parameters: {
            query?: {
                /** @description รูปแบบไฟล์รายงาน (spec §44: CSV + Excel) */
                format?: "csv" | "xlsx";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_studentReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentReportDto"];
                };
            };
        };
    };
    LineWebhookController_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LineLinkController_link: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkLineDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    LineLinkController_unlink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    MeController_attendances: {
        parameters: {
            query?: {
                /** @description หมายเลขหน้า (เริ่มที่ 1) */
                page?: number;
                /** @description จำนวนรายการต่อหน้า */
                pageSize?: number;
                /** @description คำค้นหา (contains, ไม่สนตัวพิมพ์เล็ก-ใหญ่) */
                search?: string;
                /** @description ฟิลด์ที่ใช้เรียงลำดับ (whitelist กำหนดที่แต่ละ endpoint) */
                sort?: string;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceItemDto"][];
                };
            };
        };
    };
}
