import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import pluginVue from 'eslint-plugin-vue'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.nuxt/**',
      '**/.output/**',
      '**/.cache/**',
      '**/coverage/**',
      'apps/api/src/generated/**',
      // Generated by `pnpm gen:api` — do not lint or hand-edit
      'apps/web/openapi.json',
      'apps/web/openapi.d.ts',
      '.data/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  {
    // Parse <script lang="ts"> blocks in Vue SFCs with typescript-eslint
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
  },
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
  {
    // Nuxt pages/layouts use single-word file names by convention (e.g. index.vue)
    files: ['apps/web/app/pages/**/*.vue', 'apps/web/app/layouts/**/*.vue'],
    rules: {
      'vue/multi-word-component-names': 'off',
    },
  },
  {
    // Nuxt auto-imports (ref, useAuth, definePageMeta, ...) are not visible to
    // no-undef inside .vue script blocks; vue-tsc (pnpm typecheck) covers them.
    files: ['apps/web/**/*.vue'],
    rules: {
      'no-undef': 'off',
    },
  },
  prettier,
)
